name: Release


on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag/version'     
        required: true
        default: '1.0.0'
      action_tag:
        description: 'create tag ("no" to skip)'     
        required: true
        default: ''
      release_AEPService:
        description: 'release AEPService ("no" to skip)'
        required: false
        default: 'AEPService'
      release_AEPCore:
        description: 'release AEPCore'
        required: false
        default: 'AEPCore'
      release_AEPIdentity:
        description: 'release AEPIdentity'
        required: false
        default: 'AEPIdentity'
      release_AEPLifecycle:
        description: 'release AEPLifecycle'
        required: false
        default: 'AEPLifecycle'
      release_AEPSignal:
        description: 'release AEPSignal'
        required: false
        default: 'AEPSignal'

jobs:
  release_rules_engine:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Install jq
      run: brew install jq

    - name: Check version in Podspec
      run: |
        set -eo pipefail
        echo Target version: ${{ github.event.inputs.tag }}
        make check-version VERSION=${{ github.event.inputs.tag }}
        
    - uses: release-drafter/release-drafter@v5
      if: ${{ github.event.inputs.action_tag == 'yes' }}
      with:
        name: v${{ github.event.inputs.tag }}
        tag: ${{ github.event.inputs.tag }}
        version: ${{ github.event.inputs.tag }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Pods - AEPService
      run: |
        set -eo pipefail
        gem install cocoapods
        pod lib lint AEPServices.podspec  --allow-warnings --swift-version=5.1
        pod trunk push AEPServices.podspec --allow-warnings
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    - name: Publish Pods - AEPCore
      run: |
        set -eo pipefail
        gem install cocoapods
        pod lib lint AEPCore.podspec  --allow-warnings --swift-version=5.1
        pod trunk push AEPCore.podspec --allow-warnings
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    
    - name: Publish Pods - AEPIdentity
      run: |
        set -eo pipefail
        gem install cocoapods
        pod lib lint AEPIdentity.podspec  --allow-warnings --swift-version=5.1
        pod trunk push AEPIdentity.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}   
    
    - name: Publish Pods - AEPLifecycle
      run: |
        set -eo pipefail
        gem install cocoapods
        pod lib lint AEPLifecycle.podspec  --allow-warnings --swift-version=5.1
        pod trunk push AEPLifecycle.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    - name: Publish Pods - AEPSignal
      run: |
        set -eo pipefail
        gem install cocoapods
        pod lib lint AEPSignal.podspec  --allow-warnings --swift-version=5.1
        pod trunk push AEPSignal.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        
