# This is a basic workflow that is manually triggered

name: Update AEPTestUtils Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'New version to use for the library. Example: 3.0.2'
        required: true
        
      branch:
        description: 'Branch to be used when updating versions'
        required: true

      core-dependency:
        description: 'If a version is provided, updates AEPCore and AEPServices dependency in podspec and Package.swift'
        required: false

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.inputs.branch }}
    
    - name: List Files for Debugging
      run: ls -al

    - name: List Script for Debugging
      run: ls -al Script

    - name: Print working directory for Debugging
      run: pwd

    - name: Update TestUtils
      shell: bash
      run: ./Script/update-aeptestutils-version.sh -n TestUtils -v ${{ github.event.inputs.version }} -d "AEPCore ${{ github.event.inputs.core-dependency }}, AEPServices ${{ github.event.inputs.core-dependency }}"

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        branch_name="version-${{ github.event.inputs.version }}-update"
        git checkout -b $branch_name
        git add .
        git commit -m "Updating TestUtils version to ${{ github.event.inputs.version }}."
        git push origin $branch_name
        gh pr create --base ${{ github.event.inputs.branch }} --head $branch_name --title "Updating TestUtils version to ${{ github.event.inputs.version }}" --body "Updating TestUtils version to ${{ github.event.inputs.version }}"
