name: Update AEPTestUtils Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to use for the library. Example: 3.0.2'
        required: true
        
      branch:
        description: 'Target branch for the version update pull request'
        required: true

      core-dependency:
        description: 'If a version is provided, updates AEPCore and AEPServices dependencies in podspec and Package.swift'
        required: false

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Update TestUtils
      shell: bash
      run: ./Script/update-testutils-version.sh -n TestUtils -v ${{ github.event.inputs.version }} -d "${{ github.event.inputs.core-dependency }}"

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        branch_name="version-${{ github.event.inputs.version }}-update"
        git checkout -b $branch_name
        git add .
        git commit -m "Updating TestUtils version to ${{ github.event.inputs.version }}."
        git push origin $branch_name
        gh pr create --base ${{ github.event.inputs.branch }} --head $branch_name --title "Updating TestUtils version to ${{ github.event.inputs.version }}" --body "Updating TestUtils version to ${{ github.event.inputs.version }}"
